Movie recommendation system project

Importing Libraries

In [28]:
import pandas as pd
%matplotlib inline
import matplotlib
import matplotlib.pyplot as plt
import numpy as np

In [2]:
user_col = ['user_id', 'age', 'sex', 'occupation', 'zip_code']

In [6]:
users = pd.read_csv('C:/Users/naveenkumar.ejanthka/Desktop/ml-100k/u.user', sep='|', names=user_col,encoding='latin-1')

In [7]:
rating_col = ['user_id', 'movie_id', 'rating', 'unix_timestamp']
ratings = pd.read_csv('C:/Users/naveenkumar.ejanthka/Desktop/ml-100k/u.data', sep='\t', names=rating_col,encoding='latin-1')

In [5]:
ratings

user_id  movie_id  rating  unix_timestamp
0          196       242       3       881250949
1          186       302       3       891717742
2           22       377       1       878887116
3          244        51       2       880606923
4          166       346       1       886397596
5          298       474       4       884182806
6          115       265       2       881171488
7          253       465       5       891628467
8          305       451       3       886324817
9            6        86       3       883603013
10          62       257       2       879372434
11         286      1014       5       879781125
12         200       222       5       876042340
13         210        40       3       891035994
14         224        29       3       888104457
15         303       785       3       879485318
16         122       387       5       879270459
17         194       274       2       879539794
18         291      1042       4       874834944
19         234      1184       2       892079237
20         119       392       4       886176814
21         167       486       4       892738452
22         299       144       4       877881320
23         291       118       2       874833878
24         308         1       4       887736532
25          95       546       2       879196566
26          38        95       5       892430094
27         102       768       2       883748450
28          63       277       4       875747401
29         160       234       5       876861185
...        ...       ...     ...             ...
99970      449       120       1       879959573
99971      661       762       2       876037121
99972      721       874       3       877137447
99973      821       151       4       874792889
99974      764       596       3       876243046
99975      537       443       3       886031752
99976      618       628       2       891308019
99977      487       291       3       883445079
99978      113       975       5       875936424
99979      943       391       2       888640291
99980      864       685       4       888891900
99981      750       323       3       879445877
99982      279        64       1       875308510
99983      646       750       3       888528902
99984      654       370       2       887863914
99985      617       582       4       883789294
99986      913       690       3       880824288
99987      660       229       2       891406212
99988      421       498       4       892241344
99989      495      1091       4       888637503
99990      806       421       4       882388897
99991      676       538       4       892685437
99992      721       262       3       877137285
99993      913       209       2       881367150
99994      378        78       3       880056976
99995      880       476       3       880175444
99996      716       204       5       879795543
99997      276      1090       1       874795795
99998       13       225       2       882399156
99999       12       203       3       879959583

[100000 rows x 4 columns]

In [8]:
#Reading items file:
i_cols = ['movie id', 'movie title' ,'release date','video release date', 'IMDb URL', 'unknown', 'Action', 'Adventure',
'Animation', 'Children\'s', 'Comedy', 'Crime', 'Documentary', 'Drama', 'Fantasy',
'Film-Noir', 'Horror', 'Musical', 'Mystery', 'Romance', 'Sci-Fi', 'Thriller', 'War', 'Western']

In [9]:
items = pd.read_csv('C:/Users/naveenkumar.ejanthka/Desktop/ml-100k/u.item', sep='|', names=i_cols,
encoding='latin-1')

In [11]:
items

movie id                                        movie title  \
0            1                                   Toy Story (1995)   
1            2                                   GoldenEye (1995)   
2            3                                  Four Rooms (1995)   
3            4                                  Get Shorty (1995)   
4            5                                     Copycat (1995)   
5            6  Shanghai Triad (Yao a yao yao dao waipo qiao) ...   
6            7                              Twelve Monkeys (1995)   
7            8                                        Babe (1995)   
8            9                            Dead Man Walking (1995)   
9           10                                 Richard III (1995)   
10          11                               Seven (Se7en) (1995)   
11          12                         Usual Suspects, The (1995)   
12          13                            Mighty Aphrodite (1995)   
13          14                                 Postino, Il (1994)   
14          15                          Mr. Holland's Opus (1995)   
15          16                 French Twist (Gazon maudit) (1995)   
16          17                         From Dusk Till Dawn (1996)   
17          18                          White Balloon, The (1995)   
18          19                              Antonia's Line (1995)   
19          20                          Angels and Insects (1995)   
20          21                      Muppet Treasure Island (1996)   
21          22                                  Braveheart (1995)   
22          23                                 Taxi Driver (1976)   
23          24                         Rumble in the Bronx (1995)   
24          25                               Birdcage, The (1996)   
25          26                      Brothers McMullen, The (1995)   
26          27                                    Bad Boys (1995)   
27          28                                   Apollo 13 (1995)   
28          29                              Batman Forever (1995)   
29          30                               Belle de jour (1967)   
...        ...                                                ...   
1652      1653  Entertaining Angels: The Dorothy Day Story (1996)   
1653      1654                       Chairman of the Board (1998)   
1654      1655                                  Favor, The (1994)   
1655      1656                                 Little City (1998)   
1656      1657                                      Target (1995)   
1657      1658                      Substance of Fire, The (1996)   
1658      1659                    Getting Away With Murder (1996)   
1659      1660                                 Small Faces (1995)   
1660      1661                                New Age, The (1994)   
1661      1662                                 Rough Magic (1995)   
1662      1663                            Nothing Personal (1995)   
1663      1664                     8 Heads in a Duffel Bag (1997)   
1664      1665                           Brother's Kiss, A (1997)   
1665      1666                                        Ripe (1996)   
1666      1667                              Next Step, The (1995)   
1667      1668                          Wedding Bell Blues (1996)   
1668      1669                           MURDER and murder (1996)   
1669      1670                                     Tainted (1998)   
1670      1671                          Further Gesture, A (1996)   
1671      1672                                        Kika (1993)   
1672      1673                                      Mirage (1995)   
1673      1674                                  Mamma Roma (1962)   
1674      1675                              Sunchaser, The (1996)   
1675      1676                            War at Home, The (1996)   
1676      1677                               Sweet Nothing (1995)   
1677      1678                                  Mat' i syn (1997)   
1678

In [10]:
r_cols = ['user_id', 'movie_id', 'rating', 'unix_timestamp']
ratings_train = pd.read_csv('C:/Users/naveenkumar.ejanthka/Desktop/ml-100k/ua.base', sep='\t', names=r_cols, encoding='latin-1')
ratings_test = pd.read_csv('C:/Users/naveenkumar.ejanthka/Desktop/ml-100k/ua.test', sep='\t', names=r_cols, encoding='latin-1')
ratings_train.shape, ratings_test.shape

((90570, 4), (9430, 4))

In [11]:
n_users = ratings.user_id.unique().shape[0]
n_items = ratings.movie_id.unique().shape[0]

In [12]:
data_matrix = np.zeros((n_users, n_items))
for line in ratings.itertuples():
    data_matrix[line[1]-1, line[2]-1] = line[3]
    #print line[3]
    #print data_matrix[line[1]-1, line[2]-1]

In [13]:
data_matrix

array([[5., 3., 4., ..., 0., 0., 0.],
       [4., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       ...,
       [5., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 5., 0., ..., 0., 0., 0.]])

In [14]:
from sklearn.metrics.pairwise import pairwise_distances 


In [15]:
user_similarity = pairwise_distances(data_matrix, metric='cosine')
item_similarity = pairwise_distances(data_matrix.T, metric='cosine')

In [16]:
user_similarity

array([[0.        , 0.83306902, 0.95254046, ..., 0.85138306, 0.82049212,
        0.60182526],
       [0.83306902, 0.        , 0.88940868, ..., 0.83851522, 0.82773219,
        0.89420212],
       [0.95254046, 0.88940868, 0.        , ..., 0.89875744, 0.86658385,
        0.97344413],
       ...,
       [0.85138306, 0.83851522, 0.89875744, ..., 0.        , 0.8983582 ,
        0.90488042],
       [0.82049212, 0.82773219, 0.86658385, ..., 0.8983582 , 0.        ,
        0.81753534],
       [0.60182526, 0.89420212, 0.97344413, ..., 0.90488042, 0.81753534,
        0.        ]])

In [34]:
item_similarity

array([[ 0.        ,  0.59761782,  0.66975521, ...,  1.        ,
         0.95281693,  0.95281693],
       [ 0.59761782,  0.        ,  0.72693082, ...,  1.        ,
         0.92170064,  0.92170064],
       [ 0.66975521,  0.72693082,  0.        , ...,  1.        ,
         1.        ,  0.90312495],
       ..., 
       [ 1.        ,  1.        ,  1.        , ...,  0.        ,
         1.        ,  1.        ],
       [ 0.95281693,  0.92170064,  1.        , ...,  1.        ,
         0.        ,  1.        ],
       [ 0.95281693,  0.92170064,  0.90312495, ...,  1.        ,
         1.        ,  0.        ]])

In [17]:
def predict(ratings, similarity, type='user'):
    if type == 'user':
        mean_user_rating = ratings.mean(axis=1)
        #We use np.newaxis so that mean_user_rating has same format as ratings
        ratings_diff = (ratings - mean_user_rating[:, np.newaxis])
        pred = mean_user_rating[:, np.newaxis] + similarity.dot(ratings_diff) / np.array([np.abs(similarity).sum(axis=1)]).T
    elif type == 'item':
        pred = ratings.dot(similarity) / np.array([np.abs(similarity).sum(axis=1)])
    return pred

In [18]:
user_prediction = predict(data_matrix, user_similarity, type='user')
item_prediction = predict(data_matrix, item_similarity, type='item')

In [19]:
user_prediction

array([[ 2.06532606,  0.73430275,  0.62992381, ...,  0.39359041,
         0.39304874,  0.3927712 ],
       [ 1.76308836,  0.38404019,  0.19617889, ..., -0.08837789,
        -0.0869183 , -0.08671183],
       [ 1.79590398,  0.32904733,  0.15882885, ..., -0.13699223,
        -0.13496852, -0.13476488],
       ...,
       [ 1.59151513,  0.27526889,  0.10219534, ..., -0.16735162,
        -0.16657451, -0.16641377],
       [ 1.81036267,  0.40479877,  0.27545013, ..., -0.00907358,
        -0.00846587, -0.00804858],
       [ 1.8384313 ,  0.47964837,  0.38496292, ...,  0.14686675,
         0.14629808,  0.14641455]])

In [22]:
import turicreate
import sys
!conda install --yes --prefix {sys.prefix} turicreate 
train_data = turicreate.SFrame(ratings_train)
test_data = turicreate.Sframe(ratings_test)

ModuleNotFoundError: No module named 'turicreate'